targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run
      # `dart run build_runner doctor` to check your config.
      retrofit_generator:
        generate_for:
          # Example glob for only the Dart files under `lib/models`
          #- lib/data/data_sources/remote/auth/*.dart
          #- lib/data/data_sources/remote/user/*.dart